[package]
name = "mpcemu-gui"
version = "0.1.0"
authors = []

[lib]
crate-type = ["cdylib"]

[dependencies]
mpcemu-v53 = { path = "../v53" }
wasm-bindgen = "^0.2"
wasm-bindgen-futures = "^0.4"
js-sys = "^0.3"
console_error_panic_hook = "^0.1"
